_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - 2021.10.05.06.57.40_veh-50_01658_01796
  - 2021.10.05.07.10.04_veh-52_00252_00406
  - 2021.10.05.07.10.04_veh-52_00418_00563
  - 2021.10.05.07.10.04_veh-52_00596_00663
  - 2021.10.05.07.10.04_veh-52_00689_01322
  - 2021.10.05.07.10.04_veh-52_01442_01802
  - 2021.10.05.07.38.12_veh-50_00132_00234
  - 2021.10.05.07.38.12_veh-50_00245_00433
  - 2021.10.05.07.38.12_veh-50_00898_01058
  - 2021.10.05.07.38.12_veh-50_01085_01463
  - 2021.10.05.07.38.12_veh-50_01477_01565
  - 2021.10.05.07.49.39_veh-52_00563_00680
  - 2021.10.05.07.49.39_veh-52_00770_00905
  - 2021.10.05.07.49.39_veh-52_00934_01406
  - 2021.10.05.07.49.39_veh-52_01417_01574
  - 2021.10.05.08.11.15_veh-50_00163_00321
  - 2021.10.05.08.11.15_veh-50_00360_00426
  - 2021.10.05.08.11.15_veh-50_00437_00585
  - 2021.10.05.08.11.15_veh-50_00710_00903
  - 2021.10.05.08.11.15_veh-50_00970_01211
  - 2021.10.05.08.11.15_veh-50_01222_01462
  - 2021.10.05.08.11.15_veh-50_01566_01801
  - 2021.10.06.13.21.47_veh-28_00016_00086
  - 2021.10.06.13.21.47_veh-28_00139_00216
  - 2021.10.06.13.21.47_veh-28_00262_00334
  - 2021.10.06.13.21.47_veh-28_00441_00515
  - 2021.10.06.13.21.47_veh-28_00692_00815
  - 2021.10.06.13.21.47_veh-28_01002_01116
  - 2021.10.06.13.21.47_veh-28_01127_01187
  - 2021.10.06.13.21.47_veh-28_01198_01616
  - 2021.10.06.13.21.47_veh-28_01648_01722
  - 2021.10.06.13.21.47_veh-28_01755_01829
  - 2021.10.06.14.31.13_veh-28_00014_00079
  - 2021.10.06.14.31.13_veh-28_00223_00350
  - 2021.10.06.14.31.13_veh-28_00362_00475
  - 2021.10.06.14.31.13_veh-28_00589_00665
  - 2021.10.06.14.31.13_veh-28_00738_00908
  - 2021.10.06.14.31.13_veh-28_00981_01226
  - 2021.10.06.14.31.13_veh-28_01277_01377
  - 2021.10.06.14.31.13_veh-28_01388_01849
  - 2021.10.06.17.08.46_veh-28_00016_00116
  - 2021.10.06.17.08.46_veh-28_00127_00428
  - 2021.10.06.17.08.46_veh-28_00498_00621
  - 2021.10.06.17.08.46_veh-28_00651_01030
  - 2021.10.06.17.08.46_veh-28_01127_01287
  - 2021.10.06.17.08.46_veh-28_01298_01548
  - 2021.10.06.17.08.46_veh-28_01626_01702
  - 2021.10.06.17.43.07_veh-28_00016_00291
  - 2021.10.06.17.43.07_veh-28_00302_00486
  - 2021.10.06.17.43.07_veh-28_00508_00877
  - 2021.10.06.17.43.07_veh-28_00933_01014
  - 2021.10.06.17.43.07_veh-28_01118_01302
  - 2021.10.06.17.43.07_veh-28_01354_01536
  - 2021.10.06.17.43.07_veh-28_01587_01694
  - 2021.10.06.18.52.07_veh-28_00123_00431
  - 2021.10.06.18.52.07_veh-28_00442_00578
  - 2021.10.06.18.52.07_veh-28_00592_00655
  - 2021.10.06.18.52.07_veh-28_00839_00968
  - 2021.10.06.18.52.07_veh-28_01072_01157
  - 2021.10.06.18.52.07_veh-28_01297_01462
  - 2021.10.06.18.52.07_veh-28_01474_01908
  - 2021.10.06.19.27.33_veh-28_00016_00079
  - 2021.10.06.19.27.33_veh-28_00121_00289
  - 2021.10.06.19.27.33_veh-28_00302_00794
  - 2021.10.06.19.27.33_veh-28_00805_01736
  - 2021.10.11.02.57.41_veh-50_00029_00134
  - 2021.10.11.02.57.41_veh-50_00145_00308
  - 2021.10.11.02.57.41_veh-50_00352_00535
  - 2021.10.11.02.57.41_veh-50_00704_00776
  - 2021.10.11.02.57.41_veh-50_00838_01005
  - 2021.10.11.02.57.41_veh-50_01028_01289
  - 2021.10.11.02.57.41_veh-50_01343_01501
  - 2021.10.11.02.57.41_veh-50_01522_02088
  - 2021.10.11.02.57.41_veh-50_02155_02265
  - 2021.10.11.02.57.41_veh-50_02318_02417
  - 2021.10.11.02.57.41_veh-50_02428_02548
  - 2021.10.11.05.34.05_veh-50_00020_00149
  - 2021.10.11.05.34.05_veh-50_00189_00398
  - 2021.10.11.05.34.05_veh-50_00442_00556
  - 2021.10.11.05.34.05_veh-50_00568_00631
  - 2021.10.11.05.34.05_veh-50_00697_00766
  - 2021.10.11.05.34.05_veh-50_00838_00947
  - 2021.10.11.05.34.05_veh-50_00971_01251
  - 2021.10.11.05.34.05_veh-50_01281_01692
  - 2021.10.11.05.34.05_veh-50_01718_02261
  - 2021.10.11.05.34.05_veh-50_02309_02677
  - 2021.10.11.07.12.18_veh-50_00211_00304
  - 2021.10.11.07.12.18_veh-50_00345_00498
  - 2021.10.11.07.12.18_veh-50_00541_00832
  - 2021.10.11.07.12.18_veh-50_00866_01534
  - 2021.10.11.07.12.18_veh-50_01571_01823
  - 2021.10.11.07.47.13_veh-50_00080_00159
  - 2021.10.11.07.47.13_veh-50_00202_00310
  - 2021.10.11.07.47.13_veh-50_00326_00708
  - 2021.10.11.07.47.13_veh-50_00736_00843
  - 2021.10.11.07.47.13_veh-50_00886_00952
  - 2021.10.11.07.47.13_veh-50_01020_01123
  - 2021.10.11.07.47.13_veh-50_01190_01452
  - 2021.10.11.07.47.13_veh-50_01513_02138
  - 2021.10.11.08.31.07_veh-50_00005_00242
  - 2021.10.11.08.31.07_veh-50_00282_00680
  - 2021.10.11.08.31.07_veh-50_00791_00954
  - 2021.10.11.08.31.07_veh-50_01001_01076
  - 2021.10.11.08.31.07_veh-50_01184_01318
  - 2021.10.11.08.31.07_veh-50_01365_01539
  - 2021.10.11.08.31.07_veh-50_01576_01734
  - 2021.10.11.08.31.07_veh-50_01750_01948
  - 2021.10.11.08.31.07_veh-50_01972_02057
  - 2021.10.11.08.31.07_veh-50_02146_02283
  - 2021.10.11.08.31.07_veh-50_02360_02684
