_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - 2021.06.14.20.14.09_veh-26_00024_00237
  - 2021.06.14.20.14.09_veh-26_00248_00477
  - 2021.06.14.20.14.09_veh-26_00488_00601
  - 2021.06.14.20.14.09_veh-26_00612_01016
  - 2021.06.14.20.14.09_veh-26_01027_01110
  - 2021.06.14.20.14.09_veh-26_01121_01211
  - 2021.06.23.14.06.20_veh-26_00020_01142
  - 2021.06.23.14.06.20_veh-26_01192_01541
  - 2021.06.23.14.06.20_veh-26_01563_02494
  - 2021.06.23.14.06.20_veh-26_02505_02775
  - 2021.06.23.14.54.32_veh-16_00016_00290
  - 2021.06.23.14.54.32_veh-16_00301_00410
  - 2021.06.23.14.54.32_veh-16_00421_00625
  - 2021.06.23.14.54.32_veh-16_00636_00840
  - 2021.06.23.14.54.32_veh-16_00862_01000
  - 2021.06.23.14.54.32_veh-16_01011_01166
  - 2021.06.23.14.54.32_veh-16_01187_03336
  - 2021.06.23.14.58.13_veh-35_00016_00153
  - 2021.06.23.14.58.13_veh-35_00175_00744
  - 2021.06.23.14.58.13_veh-35_00765_01108
  - 2021.06.23.14.58.13_veh-35_01130_01820
  - 2021.06.23.14.58.13_veh-35_01831_02026
  - 2021.06.23.14.58.13_veh-35_02037_04783
  - 2021.06.23.15.18.10_veh-26_00016_00143
  - 2021.06.23.15.18.10_veh-26_00165_02848
  - 2021.06.23.15.56.12_veh-16_00066_00818
  - 2021.06.23.15.56.12_veh-16_00839_01285
  - 2021.06.23.15.56.12_veh-16_01308_04289
  - 2021.06.23.16.52.00_veh-26_00038_00602
  - 2021.06.23.16.52.00_veh-26_00624_00817
  - 2021.06.23.16.52.00_veh-26_00828_01032
  - 2021.06.23.16.52.00_veh-26_01043_03099
  - 2021.06.23.16.52.00_veh-26_03120_03293
  - 2021.06.23.16.52.00_veh-26_03304_03611
  - 2021.06.23.16.54.19_veh-35_00016_00755
  - 2021.06.23.16.54.19_veh-35_00808_01256
  - 2021.06.23.16.54.19_veh-35_01277_01592
  - 2021.06.23.16.54.19_veh-35_01603_03271
  - 2021.06.23.16.54.19_veh-35_03299_03425
  - 2021.06.23.16.54.19_veh-35_03436_03683
  - 2021.06.23.16.54.19_veh-35_03705_04009
  - 2021.06.23.17.31.36_veh-16_00016_00377
  - 2021.06.23.17.31.36_veh-16_00398_00623
  - 2021.06.23.17.31.36_veh-16_00634_01421
  - 2021.06.23.17.31.36_veh-16_01443_01606
  - 2021.06.23.17.31.36_veh-16_01617_01791
  - 2021.06.23.17.31.36_veh-16_01812_01883
  - 2021.06.23.17.31.36_veh-16_01904_02129
  - 2021.06.23.17.31.36_veh-16_02150_02774
  - 2021.06.23.17.31.36_veh-16_02795_04024
  - 2021.06.23.18.23.38_veh-26_00069_00642
  - 2021.06.23.18.23.38_veh-26_00663_01217
  - 2021.06.23.18.23.38_veh-26_01238_01416
  - 2021.06.23.18.23.38_veh-26_01438_01758
  - 2021.06.23.18.23.38_veh-26_01769_01925
  - 2021.06.23.20.00.35_veh-35_00016_00119
  - 2021.06.23.20.00.35_veh-35_00130_00949
  - 2021.06.23.20.00.35_veh-35_00960_03649
  - 2021.06.23.20.00.35_veh-35_03660_04140
  - 2021.06.23.20.00.35_veh-35_04162_04257
  - 2021.06.23.20.43.31_veh-16_00016_00216
  - 2021.06.23.20.43.31_veh-16_00238_00577
  - 2021.06.23.20.43.31_veh-16_00588_00792
  - 2021.06.23.20.43.31_veh-16_00803_02194
  - 2021.06.23.20.43.31_veh-16_02216_02667
  - 2021.06.23.20.43.31_veh-16_02678_03586
  - 2021.06.23.20.43.31_veh-16_03607_04007
  - 2021.06.23.21.56.29_veh-35_00097_00209
  - 2021.06.23.21.56.29_veh-35_00220_00936
  - 2021.06.23.21.56.29_veh-35_00947_01581
  - 2021.06.23.21.56.29_veh-35_01603_02401
  - 2021.06.23.21.56.29_veh-35_02412_03161
  - 2021.06.23.22.05.48_veh-16_00015_00276
  - 2021.06.23.22.05.48_veh-16_00287_00591
  - 2021.06.23.22.05.48_veh-16_00602_00800
  - 2021.07.09.01.37.16_veh-26_00692_00762
  - 2021.07.09.01.37.16_veh-26_00936_00996
  - 2021.07.09.01.37.16_veh-26_01336_01396
  - 2021.07.09.01.37.16_veh-26_01726_01793
  - 2021.07.09.01.37.16_veh-26_02856_02932
  - 2021.07.09.01.37.16_veh-26_03306_03373
  - 2021.07.09.01.37.16_veh-26_03432_03503
  - 2021.07.09.01.37.16_veh-26_04224_04293
  - 2021.07.09.01.37.16_veh-26_04675_04767
  - 2021.07.09.01.37.16_veh-26_04815_04878
  - 2021.07.09.01.37.16_veh-26_05530_05595
  - 2021.07.09.01.37.16_veh-26_05710_05791
  - 2021.07.09.02.42.50_veh-35_00038_02629
  - 2021.07.09.02.42.50_veh-35_02651_02770
  - 2021.07.09.15.53.28_veh-38_00053_00163
  - 2021.07.09.15.53.28_veh-38_00184_02293
  - 2021.07.09.15.53.28_veh-38_02316_03434
  - 2021.07.09.15.53.28_veh-38_03528_04262
  - 2021.07.09.15.53.28_veh-38_04273_04767
  - 2021.07.09.15.53.28_veh-38_04778_04886
  - 2021.07.09.16.12.19_veh-26_02509_02592
  - 2021.07.09.16.12.19_veh-26_02985_03053
  - 2021.07.09.16.12.19_veh-26_04434_04498
  - 2021.07.09.16.12.19_veh-26_05071_05149
  - 2021.07.09.16.12.19_veh-26_06527_06591
  - 2021.07.09.16.12.19_veh-26_06964_07035
  - 2021.07.09.16.12.19_veh-26_07208_07271
  - 2021.07.09.17.06.37_veh-35_00049_00237
  - 2021.07.09.17.06.37_veh-35_00258_00748
  - 2021.07.09.17.06.37_veh-35_00769_00907
  - 2021.07.09.17.06.37_veh-35_00928_02567
  - 2021.07.09.17.06.37_veh-35_02609_05015
  - 2021.07.09.17.06.37_veh-35_05026_05593
  - 2021.07.09.20.26.06_veh-35_00016_01757
  - 2021.07.09.20.26.06_veh-35_01768_02782
  - 2021.07.09.20.26.06_veh-35_02793_03289
  - 2021.07.09.20.26.06_veh-35_03314_03877
  - 2021.07.09.20.26.06_veh-35_03898_05974
  - 2021.07.09.20.59.12_veh-38_00113_00669
  - 2021.07.09.20.59.12_veh-38_00690_00762
  - 2021.07.09.20.59.12_veh-38_00773_01187
  - 2021.07.09.20.59.12_veh-38_01208_01692
  - 2021.07.09.20.59.12_veh-38_01713_01842
  - 2021.07.09.20.59.12_veh-38_01853_02043
  - 2021.07.09.20.59.12_veh-38_02064_03281
  - 2021.07.09.20.59.12_veh-38_03292_04331
  - 2021.07.09.20.59.12_veh-38_04342_05676
  - 2021.07.09.20.59.12_veh-38_05697_06861
  - 2021.07.09.20.59.12_veh-38_06872_07220
  - 2021.07.09.20.59.12_veh-38_07245_07341
  - 2021.07.09.23.23.48_veh-26_00054_01295
  - 2021.07.09.23.23.48_veh-26_01319_01432
  - 2021.07.09.23.23.48_veh-26_01454_02217
  - 2021.07.09.23.23.48_veh-26_02228_04624
  - 2021.07.09.23.23.48_veh-26_04648_06327
  - 2021.07.16.00.24.14_veh-38_00094_00346
  - 2021.07.16.00.24.14_veh-38_00367_01154
  - 2021.07.16.00.24.14_veh-38_01165_01425
  - 2021.07.16.00.24.14_veh-38_01447_01621
  - 2021.07.16.00.51.05_veh-17_00023_01331
  - 2021.07.16.00.51.05_veh-17_01352_01901
  - 2021.07.16.00.51.05_veh-17_01938_03243
  - 2021.07.16.00.51.05_veh-17_03264_05261
  - 2021.07.16.01.22.41_veh-14_00015_00547
  - 2021.07.16.01.22.41_veh-14_00572_01716
  - 2021.07.16.01.22.41_veh-14_01737_01980
  - 2021.07.16.01.22.41_veh-14_02003_02615
  - 2021.07.16.01.22.41_veh-14_02626_04289
  - 2021.07.16.01.22.41_veh-14_04315_07102
  - 2021.07.16.02.53.40_veh-17_00016_01588
  - 2021.07.16.16.01.30_veh-38_00016_00333
  - 2021.07.16.16.01.30_veh-38_00356_02486
  - 2021.07.16.16.01.30_veh-38_02497_03871
  - 2021.07.16.16.01.30_veh-38_03893_05253
  - 2021.07.16.16.01.30_veh-38_05274_05744
  - 2021.07.16.16.01.30_veh-38_05766_06843
  - 2021.07.16.16.08.35_veh-35_00132_00784
  - 2021.07.16.16.08.35_veh-35_00805_01292
  - 2021.07.16.16.08.35_veh-35_01303_01641
  - 2021.07.16.16.08.35_veh-35_01664_02376
  - 2021.07.16.16.08.35_veh-35_02397_02540
  - 2021.07.16.16.08.35_veh-35_02551_02640
  - 2021.07.16.16.08.35_veh-35_02651_03700
  - 2021.07.16.16.08.35_veh-35_03711_04709
  - 2021.07.16.16.08.35_veh-35_04744_06051
  - 2021.07.16.16.27.22_veh-26_00016_01515
  - 2021.07.16.16.27.22_veh-26_01536_02260
  - 2021.07.16.16.27.22_veh-26_02282_03814
  - 2021.07.16.16.27.22_veh-26_03836_05047
  - 2021.07.16.16.27.22_veh-26_05058_05383
  - 2021.07.16.16.27.22_veh-26_05416_05596
  - 2021.07.16.18.06.21_veh-38_00016_00747
  - 2021.07.16.18.06.21_veh-38_00770_01505
  - 2021.07.16.18.06.21_veh-38_01526_02150
  - 2021.07.16.18.06.21_veh-38_02197_03220
  - 2021.07.16.18.06.21_veh-38_03231_03712
  - 2021.07.16.18.06.21_veh-38_03733_04300
  - 2021.07.16.18.06.21_veh-38_04311_04460
  - 2021.07.16.18.06.21_veh-38_04471_04922
  - 2021.07.16.18.06.21_veh-38_04933_05307
  - 2021.07.16.18.06.21_veh-38_05338_05486
  - 2021.07.16.18.19.22_veh-35_00023_00234
  - 2021.07.16.18.19.22_veh-35_00255_00418
  - 2021.07.16.18.19.22_veh-35_00440_00858
  - 2021.07.16.18.19.22_veh-35_00869_03454
  - 2021.07.16.18.49.56_veh-26_00015_00235
  - 2021.07.16.18.49.56_veh-26_00256_00822
  - 2021.07.16.18.49.56_veh-26_00833_03384
  - 2021.07.16.18.49.56_veh-26_03407_03538
  - 2021.07.16.20.45.29_veh-35_00016_00589
  - 2021.07.16.20.45.29_veh-35_00600_01084
  - 2021.07.16.20.45.29_veh-35_01095_01486
  - 2021.07.16.20.45.29_veh-35_01513_02486
  - 2021.07.16.20.45.29_veh-35_02509_02649
  - 2021.07.16.21.17.55_veh-26_00715_00781
  - 2021.07.16.21.17.55_veh-26_00872_00937
  - 2021.07.16.21.17.55_veh-26_01014_01075
  - 2021.07.16.21.17.55_veh-26_01392_01488
  - 2021.07.16.21.17.55_veh-26_02927_02992
  - 2021.07.16.21.17.55_veh-26_03254_03336
  - 2021.07.16.21.17.55_veh-26_03772_03842
  - 2021.07.16.21.17.55_veh-26_03860_03930
  - 2021.07.16.21.17.55_veh-26_04426_04488
  - 2021.07.16.21.17.55_veh-26_05156_05225
  - 2021.07.16.21.17.55_veh-26_05558_05627
  - 2021.07.16.22.40.23_veh-38_00016_00182
  - 2021.07.16.22.40.23_veh-38_00204_00360
  - 2021.07.16.22.40.23_veh-38_00371_00797
  - 2021.07.16.22.40.23_veh-38_00818_03032
  - 2021.07.16.23.22.27_veh-14_00015_01368
  - 2021.07.16.23.22.27_veh-14_01383_01479
  - 2021.07.16.23.22.27_veh-14_01502_01610
  - 2021.07.16.23.22.27_veh-14_01631_03833
  - 2021.07.16.23.22.27_veh-14_03844_04474
  - 2021.07.16.23.22.27_veh-14_04496_06203
  - 2021.07.16.23.22.27_veh-14_06214_06318
  - 2021.07.16.23.22.27_veh-14_06339_07673
  - 2021.07.24.16.07.03_veh-35_01649_01813
  - 2021.07.24.16.48.51_veh-17_00016_00166
  - 2021.07.24.18.06.35_veh-35_03664_03799
  - 2021.07.24.20.37.45_veh-17_00015_00375
  - 2021.07.24.22.52.16_veh-35_03236_04096
  - 2021.07.24.23.50.16_veh-17_01696_02071
  - 2021.08.09.17.55.59_veh-28_00021_00307
  - 2021.08.09.17.55.59_veh-28_00320_00544
  - 2021.08.09.17.55.59_veh-28_00558_00680
  - 2021.08.09.17.55.59_veh-28_00691_00876
  - 2021.08.09.17.55.59_veh-28_00960_01031
  - 2021.08.09.17.55.59_veh-28_01065_01167
  - 2021.08.09.18.37.41_veh-28_00053_00548
  - 2021.08.09.18.37.41_veh-28_00648_00730
  - 2021.08.17.13.10.50_veh-08_00122_00295
  - 2021.08.17.13.10.50_veh-08_00313_00564
  - 2021.08.17.13.10.50_veh-08_00726_01027
  - 2021.08.17.13.10.50_veh-08_01060_01340
  - 2021.08.17.13.15.12_veh-45_00168_00302
  - 2021.08.17.13.15.12_veh-45_00324_00489
  - 2021.08.17.13.15.12_veh-45_00565_00643
  - 2021.08.17.13.15.12_veh-45_00691_00794
  - 2021.08.17.13.15.12_veh-45_00819_00884
  - 2021.08.17.13.15.12_veh-45_00925_00987
  - 2021.08.17.13.15.12_veh-45_01049_01467
  - 2021.08.17.13.15.12_veh-45_01517_01668
  - 2021.08.17.13.15.12_veh-45_01679_01816
  - 2021.08.17.13.15.12_veh-45_02025_02103
  - 2021.08.17.13.15.12_veh-45_02124_02293
  - 2021.08.17.13.15.12_veh-45_02304_02650
  - 2021.08.17.14.32.33_veh-08_00016_00354
  - 2021.08.17.14.32.33_veh-08_00390_00468
  - 2021.08.17.14.32.33_veh-08_00521_01051
  - 2021.08.17.14.32.33_veh-08_01072_01231
  - 2021.08.17.14.32.33_veh-08_01262_01528
  - 2021.08.17.14.32.33_veh-08_01576_01919
  - 2021.08.17.14.45.12_veh-42_00092_00301
  - 2021.08.17.14.45.12_veh-42_00312_00531
  - 2021.08.17.14.45.12_veh-42_00542_00803
  - 2021.08.17.14.45.12_veh-42_00831_01079
  - 2021.08.17.14.45.12_veh-42_01119_01535
  - 2021.08.17.14.45.12_veh-42_01562_01754
  - 2021.08.17.14.45.12_veh-42_01866_01999
  - 2021.08.17.15.02.08_veh-45_00167_00480
  - 2021.08.17.15.02.08_veh-45_00505_00606
  - 2021.08.17.15.02.08_veh-45_00723_00823
  - 2021.08.17.15.02.08_veh-45_00860_01324
  - 2021.08.17.15.02.08_veh-45_01348_01731
  - 2021.08.17.15.02.08_veh-45_01756_01966
  - 2021.08.17.15.02.08_veh-45_02003_02086
  - 2021.08.17.15.02.08_veh-45_02111_02303
  - 2021.08.17.15.02.08_veh-45_02452_02521
  - 2021.08.17.16.48.45_veh-43_00114_00415
  - 2021.08.17.16.48.45_veh-43_00451_00871
  - 2021.08.17.16.48.45_veh-43_00936_01035
  - 2021.08.17.16.48.45_veh-43_01060_01405
  - 2021.08.17.16.48.45_veh-43_01439_01665
  - 2021.08.17.16.48.45_veh-43_01676_01764
  - 2021.08.17.16.48.45_veh-43_01837_02038
  - 2021.08.17.16.48.45_veh-43_02070_02652
  - 2021.08.17.16.48.45_veh-43_02693_03062
  - 2021.08.17.16.48.45_veh-43_03137_03245
  - 2021.08.17.16.48.45_veh-43_03268_03352
  - 2021.08.17.16.48.45_veh-43_03384_03788
  - 2021.08.17.16.57.11_veh-08_00206_00331
  - 2021.08.17.16.57.11_veh-08_00354_01167
  - 2021.08.17.16.57.11_veh-08_01200_01636
  - 2021.08.17.17.17.01_veh-45_00123_00191
  - 2021.08.17.17.17.01_veh-45_00207_00594
  - 2021.08.17.17.17.01_veh-45_00762_01166
  - 2021.08.17.17.17.01_veh-45_01207_01417
  - 2021.08.17.17.17.01_veh-45_01443_01678
  - 2021.08.17.17.17.01_veh-45_01796_02069
  - 2021.08.17.17.17.01_veh-45_02098_02251
  - 2021.08.17.17.17.01_veh-45_02314_02798
  - 2021.08.17.17.55.18_veh-43_00016_00083
  - 2021.08.17.17.55.18_veh-43_00122_00325
  - 2021.08.17.17.55.18_veh-43_00358_00673
  - 2021.08.17.17.55.18_veh-43_00802_01030
  - 2021.08.17.17.55.18_veh-43_01240_01704
  - 2021.08.17.18.11.12_veh-08_00083_00200
  - 2021.08.17.18.11.12_veh-08_00234_00611
  - 2021.08.17.18.11.12_veh-08_00629_01599
  - 2021.08.17.18.11.12_veh-08_01622_01709
  - 2021.08.17.18.13.38_veh-45_00016_00127
  - 2021.08.17.18.13.38_veh-45_00151_00387
  - 2021.08.17.18.13.38_veh-45_00410_00618
  - 2021.08.17.18.13.38_veh-45_00641_00881