_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - 2021.05.12.19.36.12_veh-35_00005_00204
  - 2021.05.12.19.36.12_veh-35_00215_00405
  - 2021.05.12.19.36.12_veh-35_00416_00557
  - 2021.05.12.19.36.12_veh-35_00568_01168
  - 2021.05.12.19.36.12_veh-35_01179_01278
  - 2021.05.12.19.36.12_veh-35_01305_01389
  - 2021.05.12.19.36.12_veh-35_01400_01643
  - 2021.05.12.19.36.12_veh-35_01654_01733
  - 2021.05.12.19.36.12_veh-35_01744_01934
  - 2021.05.12.19.36.12_veh-35_01945_02065
  - 2021.05.12.19.36.12_veh-35_02079_02176
  - 2021.05.12.22.00.38_veh-35_00005_00118
  - 2021.05.12.22.00.38_veh-35_00129_00204
  - 2021.05.12.22.00.38_veh-35_00215_00995
  - 2021.05.12.22.00.38_veh-35_01008_01518
  - 2021.05.12.22.28.35_veh-35_00025_00115
  - 2021.05.12.22.28.35_veh-35_00126_00339
  - 2021.05.12.22.28.35_veh-35_00350_00568
  - 2021.05.12.22.28.35_veh-35_00620_01164
  - 2021.05.12.22.28.35_veh-35_01175_02127
  - 2021.05.12.22.28.35_veh-35_02138_02481
  - 2021.05.12.23.36.44_veh-35_00063_00141
  - 2021.05.12.23.36.44_veh-35_00152_00504
  - 2021.05.12.23.36.44_veh-35_00515_00701
  - 2021.05.12.23.36.44_veh-35_00712_00774
  - 2021.05.12.23.36.44_veh-35_00785_01041
  - 2021.05.12.23.36.44_veh-35_01133_01535
  - 2021.05.12.23.36.44_veh-35_01585_01724
  - 2021.05.12.23.36.44_veh-35_01735_01957
  - 2021.05.12.23.36.44_veh-35_02035_02387
  - 2021.06.07.11.59.52_veh-35_02283_02464
  - 2021.06.07.12.42.11_veh-38_01777_02078
  - 2021.06.07.12.42.11_veh-38_02445_02843
  - 2021.06.07.12.42.11_veh-38_03254_03455
  - 2021.06.07.12.54.00_veh-35_01843_02314
  - 2021.06.07.13.53.57_veh-35_01772_02032
  - 2021.06.07.13.53.57_veh-35_02489_03145
  - 2021.06.07.17.46.49_veh-35_02607_03120
  - 2021.06.07.17.46.49_veh-35_04084_04828
  - 2021.06.07.17.46.49_veh-35_04839_05184
  - 2021.06.07.17.48.02_veh-38_01949_02085
  - 2021.06.07.18.53.26_veh-26_00005_00427
  - 2021.06.07.18.53.26_veh-26_01208_01412
  - 2021.06.07.19.29.59_veh-38_00474_00922
  - 2021.06.07.19.29.59_veh-38_01025_01274
  - 2021.06.07.19.29.59_veh-38_02615_02779
  - 2021.06.07.19.43.00_veh-35_01782_01986
  - 2021.06.07.19.43.00_veh-35_02298_02525
  - 2021.06.08.12.00.19_veh-35_01722_02119
  - 2021.06.08.12.00.19_veh-35_02135_02369
  - 2021.06.08.12.00.19_veh-35_02988_03160
  - 2021.06.08.12.00.19_veh-35_03451_03644
  - 2021.06.08.12.00.19_veh-35_03655_03792
  - 2021.06.08.12.00.19_veh-35_04422_04725
  - 2021.06.08.12.00.19_veh-35_05235_05578
  - 2021.06.08.12.10.22_veh-38_01912_02498
  - 2021.06.08.12.10.22_veh-38_05512_05652
  - 2021.06.08.12.54.54_veh-26_00015_00507
  - 2021.06.08.12.54.54_veh-26_00733_00983
  - 2021.06.08.12.54.54_veh-26_01289_01417
  - 2021.06.08.12.54.54_veh-26_02323_02479
  - 2021.06.08.12.54.54_veh-26_02994_03970
  - 2021.06.08.12.54.54_veh-26_04262_04732
  - 2021.06.08.14.14.51_veh-35_00893_01188
  - 2021.06.08.14.14.51_veh-35_01508_01763
  - 2021.06.08.14.35.24_veh-26_01989_02235
  - 2021.06.08.14.35.24_veh-26_02555_03004
  - 2021.06.08.14.36.49_veh-38_00312_00694
  - 2021.06.08.16.31.33_veh-38_00015_00262
  - 2021.06.08.16.31.33_veh-38_01589_02072
  - 2021.06.08.16.31.33_veh-38_03406_03605
  - 2021.06.08.16.31.33_veh-38_04275_04425
  - 2021.06.08.17.25.03_veh-35_02448_02655
  - 2021.06.08.17.25.03_veh-35_03522_03716
  - 2021.06.08.17.36.50_veh-26_03873_04225
  - 2021.06.08.17.36.50_veh-26_05134_05378
  - 2021.06.08.18.18.30_veh-38_01241_01417
  - 2021.06.08.18.18.30_veh-38_05578_05988
  - 2021.06.08.18.18.30_veh-38_06017_06142
  - 2021.06.08.18.59.48_veh-12_01276_01459
  - 2021.06.08.18.59.48_veh-12_02116_02247
  - 2021.06.08.18.59.48_veh-12_03122_03677
  - 2021.06.08.19.16.23_veh-26_00193_00322
  - 2021.06.08.19.16.23_veh-26_00973_01139
  - 2021.06.08.19.16.23_veh-26_01782_01967
  - 2021.06.09.11.54.15_veh-12_00015_00259
  - 2021.06.09.11.54.15_veh-12_00270_00339
  - 2021.06.09.11.54.15_veh-12_00361_00678
  - 2021.06.09.11.54.15_veh-12_00689_01229
  - 2021.06.09.11.54.15_veh-12_01240_01361
  - 2021.06.09.11.54.15_veh-12_01403_01526
  - 2021.06.09.11.54.15_veh-12_01537_01628
  - 2021.06.09.11.54.15_veh-12_01705_01845
  - 2021.06.09.11.54.15_veh-12_01902_02277
  - 2021.06.09.11.54.15_veh-12_02288_02529
  - 2021.06.09.11.54.15_veh-12_02540_02723
  - 2021.06.09.11.54.15_veh-12_02734_02946
  - 2021.06.09.11.54.15_veh-12_02957_03110
  - 2021.06.09.11.54.15_veh-12_03121_03319
  - 2021.06.09.11.54.15_veh-12_03371_03642
  - 2021.06.09.11.54.15_veh-12_03653_03902
  - 2021.06.09.11.54.15_veh-12_03917_04069
  - 2021.06.09.11.54.15_veh-12_04138_04355
  - 2021.06.09.11.54.15_veh-12_04366_04810
  - 2021.06.09.11.54.15_veh-12_04821_05096
  - 2021.06.09.11.54.15_veh-12_05108_05331
  - 2021.06.09.11.54.15_veh-12_05342_05403
  - 2021.06.09.11.54.15_veh-12_05414_05511
  - 2021.06.09.11.54.15_veh-12_05543_05765
  - 2021.06.09.12.06.35_veh-35_00149_00262
  - 2021.06.09.12.06.35_veh-35_00284_00410
  - 2021.06.09.12.06.35_veh-35_00422_01112
  - 2021.06.09.12.06.35_veh-35_01164_01494
  - 2021.06.09.12.39.51_veh-26_00055_00360
  - 2021.06.09.12.39.51_veh-26_00371_00480
  - 2021.06.09.12.39.51_veh-26_00492_00587
  - 2021.06.09.12.39.51_veh-26_00609_01168
  - 2021.06.09.12.39.51_veh-26_01179_01338
  - 2021.06.09.12.39.51_veh-26_01418_01480
  - 2021.06.09.12.39.51_veh-26_01491_01642
  - 2021.06.09.12.39.51_veh-26_01653_01919
  - 2021.06.09.12.39.51_veh-26_01943_02303
  - 2021.06.09.12.39.51_veh-26_02338_02459
  - 2021.06.09.12.39.51_veh-26_02470_02648
  - 2021.06.09.12.39.51_veh-26_02729_02878
  - 2021.06.09.12.39.51_veh-26_02901_02978
  - 2021.06.09.12.39.51_veh-26_02989_03385
  - 2021.06.09.12.39.51_veh-26_03409_03722
  - 2021.06.09.12.39.51_veh-26_03733_03918
  - 2021.06.09.12.39.51_veh-26_03951_04180
  - 2021.06.09.12.39.51_veh-26_04255_04331
  - 2021.06.09.12.39.51_veh-26_04374_04513
  - 2021.06.09.12.39.51_veh-26_04543_05321
  - 2021.06.09.12.39.51_veh-26_05332_05540
  - 2021.06.09.12.39.51_veh-26_05620_06003
  - 2021.06.09.12.51.31_veh-35_00007_00089
  - 2021.06.09.12.51.31_veh-35_00100_00277
  - 2021.06.09.12.51.31_veh-35_00288_00529
  - 2021.06.09.12.51.31_veh-35_00540_00631
  - 2021.06.09.12.51.31_veh-35_00697_00820
  - 2021.06.09.12.51.31_veh-35_00852_01020
  - 2021.06.09.12.51.31_veh-35_01047_01415
  - 2021.06.09.12.51.31_veh-35_01427_01576
  - 2021.06.09.12.51.31_veh-35_01587_01718
  - 2021.06.09.12.51.31_veh-35_01729_02626
  - 2021.06.09.12.51.31_veh-35_02677_02842
  - 2021.06.09.12.51.31_veh-35_02853_02964
  - 2021.06.09.12.51.31_veh-35_02975_03207
  - 2021.06.09.12.51.31_veh-35_03229_03360
  - 2021.06.09.12.51.31_veh-35_03371_03476
  - 2021.06.09.12.51.31_veh-35_03487_03821
  - 2021.06.09.12.51.31_veh-35_03869_04221
  - 2021.06.09.12.51.31_veh-35_04247_04424
  - 2021.06.09.12.51.31_veh-35_04435_04593
  - 2021.06.09.12.51.31_veh-35_04715_04871
  - 2021.06.09.12.51.31_veh-35_04882_05013
  - 2021.06.09.12.51.31_veh-35_05024_05275
  - 2021.06.09.12.51.31_veh-35_05299_05468
  - 2021.06.09.14.03.17_veh-12_00015_00099
  - 2021.06.09.14.03.17_veh-12_00159_00283
  - 2021.06.09.14.03.17_veh-12_00294_00364
  - 2021.06.09.14.03.17_veh-12_00375_00566
  - 2021.06.09.14.03.17_veh-12_00711_00839
  - 2021.06.09.14.03.17_veh-12_00859_00931
  - 2021.06.09.14.03.17_veh-12_01094_01213
  - 2021.06.09.14.03.17_veh-12_01225_01437
  - 2021.06.09.14.03.17_veh-12_01603_01708
  - 2021.06.09.14.03.17_veh-12_01883_01955
  - 2021.06.09.14.03.17_veh-12_02011_02101
  - 2021.06.09.14.03.17_veh-12_02112_02202
  - 2021.06.09.14.03.17_veh-12_02213_02304
  - 2021.06.09.14.03.17_veh-12_02495_02573
  - 2021.06.09.14.03.17_veh-12_02584_02970
  - 2021.06.09.14.03.17_veh-12_03014_03120
  - 2021.06.09.14.03.17_veh-12_03200_03333
  - 2021.06.09.14.03.17_veh-12_03344_03461
  - 2021.06.09.14.03.17_veh-12_03584_03667
  - 2021.06.09.14.03.17_veh-12_03678_03787
  - 2021.06.09.14.03.17_veh-12_03798_04118
  - 2021.06.09.14.03.17_veh-12_04129_04237
  - 2021.06.09.14.50.36_veh-26_00063_00350
  - 2021.06.09.14.50.36_veh-26_00598_00665
  - 2021.06.09.14.50.36_veh-26_00677_00819
  - 2021.06.09.14.50.36_veh-26_00832_00905
  - 2021.06.09.14.50.36_veh-26_01037_01113
  - 2021.06.09.14.50.36_veh-26_01124_01198
  - 2021.06.09.14.50.36_veh-26_01209_01393
  - 2021.06.09.14.50.36_veh-26_01537_01600
  - 2021.06.09.14.50.36_veh-26_01698_01771
  - 2021.06.09.14.50.36_veh-26_01782_02044
  - 2021.06.09.14.50.36_veh-26_02081_02143
  - 2021.06.09.14.50.36_veh-26_02376_02484
  - 2021.06.09.14.50.36_veh-26_02495_02669
  - 2021.06.09.14.50.36_veh-26_02680_02781
  - 2021.06.09.14.50.36_veh-26_02826_02955
  - 2021.06.09.14.50.36_veh-26_03061_03152
  - 2021.06.09.14.50.36_veh-26_03208_03299
  - 2021.06.09.14.50.36_veh-26_03310_03392
  - 2021.06.09.14.50.36_veh-26_03403_03496
  - 2021.06.09.14.50.36_veh-26_03507_03584
  - 2021.06.09.14.50.36_veh-26_03595_03863
  - 2021.06.09.14.50.36_veh-26_03874_04112
  - 2021.06.09.14.50.36_veh-26_04123_04185
  - 2021.06.09.14.50.36_veh-26_04226_04484
  - 2021.06.09.14.50.36_veh-26_04495_04561
  - 2021.06.09.14.50.36_veh-26_04605_04729
  - 2021.06.09.14.50.36_veh-26_04746_04837
  - 2021.06.09.14.50.36_veh-26_05055_05138
  - 2021.06.09.14.50.36_veh-26_05225_05311
  - 2021.06.09.14.50.36_veh-26_05326_05387
  - 2021.06.09.14.50.36_veh-26_05398_05800
  - 2021.06.09.14.50.36_veh-26_05825_05901
  - 2021.06.09.14.58.55_veh-35_00016_00182
  - 2021.06.09.14.58.55_veh-35_00193_01084
  - 2021.06.09.14.58.55_veh-35_01095_01484
  - 2021.06.09.14.58.55_veh-35_01496_01664
  - 2021.06.09.14.58.55_veh-35_01675_01774
  - 2021.06.09.14.58.55_veh-35_01785_01883
  - 2021.06.09.14.58.55_veh-35_01894_02311
  - 2021.06.09.14.58.55_veh-35_02388_02465
  - 2021.06.09.14.58.55_veh-35_02476_02569
  - 2021.06.09.14.58.55_veh-35_02580_02649
  - 2021.06.09.14.58.55_veh-35_02660_02757
  - 2021.06.09.14.58.55_veh-35_02778_02850
  - 2021.06.09.14.58.55_veh-35_02861_03037
  - 2021.06.09.14.58.55_veh-35_03048_03301
  - 2021.06.09.14.58.55_veh-35_03312_03379
  - 2021.06.09.14.58.55_veh-35_03390_03537
  - 2021.06.09.14.58.55_veh-35_03548_03800
  - 2021.06.09.14.58.55_veh-35_03811_03916
  - 2021.06.09.14.58.55_veh-35_03927_04034
  - 2021.06.09.14.58.55_veh-35_04047_04349
  - 2021.06.09.14.58.55_veh-35_04360_04484
  - 2021.06.09.14.58.55_veh-35_04541_04657
  - 2021.06.09.14.58.55_veh-35_04695_05321
  - 2021.06.09.14.58.55_veh-35_05473_05626
  - 2021.06.09.14.58.55_veh-35_05655_05745
  - 2021.06.09.17.23.18_veh-38_00016_00120
  - 2021.06.09.17.23.18_veh-38_00131_00294
  - 2021.06.09.17.23.18_veh-38_00305_00597
  - 2021.06.09.17.23.18_veh-38_00609_00762
  - 2021.06.09.17.23.18_veh-38_00773_01140
  - 2021.06.09.17.23.18_veh-38_01151_01532
  - 2021.06.09.17.23.18_veh-38_01598_01750
  - 2021.06.09.17.23.18_veh-38_01761_02019
  - 2021.06.09.17.23.18_veh-38_02094_02305
  - 2021.06.09.17.23.18_veh-38_02316_02391
  - 2021.06.09.17.23.18_veh-38_02450_02515
  - 2021.06.09.17.23.18_veh-38_02526_03027
  - 2021.06.09.17.23.18_veh-38_03095_03280
  - 2021.06.09.17.23.18_veh-38_03302_03414
  - 2021.06.09.17.23.18_veh-38_03425_04047
  - 2021.06.09.17.23.18_veh-38_04163_04245
  - 2021.06.09.17.23.18_veh-38_04286_04521
  - 2021.06.09.17.23.18_veh-38_04544_04697
  - 2021.06.09.17.23.18_veh-38_04708_04770
  - 2021.06.09.17.23.18_veh-38_04782_05228
  - 2021.06.09.17.23.18_veh-38_05239_05412
  - 2021.06.09.17.23.18_veh-38_05423_05550
  - 2021.06.09.17.23.18_veh-38_05602_05695
  - 2021.06.09.17.37.09_veh-12_00016_00140
  - 2021.06.09.17.37.09_veh-12_00151_00393
  - 2021.06.09.17.37.09_veh-12_00404_00864
  - 2021.06.09.17.37.09_veh-12_00875_01204
  - 2021.06.09.17.37.09_veh-12_01215_01375
  - 2021.06.09.17.37.09_veh-12_01386_01454
  - 2021.06.09.17.37.09_veh-12_01465_01790
  - 2021.06.09.17.37.09_veh-12_01801_01925
  - 2021.06.09.17.37.09_veh-12_01936_02067
  - 2021.06.09.17.37.09_veh-12_02082_02170
  - 2021.06.09.17.37.09_veh-12_02239_02313
  - 2021.06.09.17.37.09_veh-12_02324_02434
  - 2021.06.09.17.37.09_veh-12_02445_02566
  - 2021.06.09.17.37.09_veh-12_02639_02992
  - 2021.06.09.17.37.09_veh-12_03003_03121
  - 2021.06.09.17.37.09_veh-12_03132_03193
  - 2021.06.09.17.37.09_veh-12_03219_03372
  - 2021.06.09.17.37.09_veh-12_03420_03578
  - 2021.06.09.17.37.09_veh-12_03600_03810
  - 2021.06.09.17.37.09_veh-12_03830_04329
  - 2021.06.09.17.37.09_veh-12_04340_04478
  - 2021.06.09.17.37.09_veh-12_04489_04816
  - 2021.06.09.18.23.43_veh-35_00026_00274
  - 2021.06.09.18.23.43_veh-35_00349_00544
  - 2021.06.09.18.23.43_veh-35_00555_00726
  - 2021.06.09.18.23.43_veh-35_00799_01004
  - 2021.06.09.18.23.43_veh-35_01028_01221
  - 2021.06.09.18.23.43_veh-35_01232_01405
  - 2021.06.09.18.23.43_veh-35_01416_01573
  - 2021.06.09.18.23.43_veh-35_01584_01691
  - 2021.06.09.18.23.43_veh-35_01702_01928
  - 2021.06.09.18.23.43_veh-35_01939_02025
  - 2021.06.09.18.23.43_veh-35_02086_02333
  - 2021.06.09.18.23.43_veh-35_02344_02669
  - 2021.06.09.18.23.43_veh-35_02680_02868
  - 2021.06.09.18.23.43_veh-35_02945_03099
  - 2021.06.09.18.23.43_veh-35_03110_03179
  - 2021.06.09.18.23.43_veh-35_03190_03392
  - 2021.06.09.18.23.43_veh-35_03403_03481
  - 2021.06.09.18.23.43_veh-35_03500_03586