_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - 2021.08.17.18.13.38_veh-45_00946_01854
  - 2021.08.17.18.43.12_veh-43_00125_00805
  - 2021.08.17.18.43.12_veh-43_01023_01358
  - 2021.08.17.18.43.12_veh-43_01390_01589
  - 2021.08.17.18.43.12_veh-43_01611_01812
  - 2021.08.17.18.43.12_veh-43_01906_02722
  - 2021.08.17.18.43.12_veh-43_02784_02851
  - 2021.08.17.18.43.12_veh-43_02889_03258
  - 2021.08.17.18.43.12_veh-43_03294_03490
  - 2021.08.17.18.44.32_veh-08_00016_00564
  - 2021.08.17.18.44.32_veh-08_00586_00848
  - 2021.08.17.18.44.32_veh-08_00873_01540
  - 2021.08.17.18.54.02_veh-45_00016_00304
  - 2021.08.17.18.54.02_veh-45_00511_00579
  - 2021.08.17.18.54.02_veh-45_00665_01065
  - 2021.08.17.18.54.02_veh-45_01103_01238
  - 2021.08.17.18.54.02_veh-45_01261_02086
  - 2021.08.17.18.54.02_veh-45_02105_02189
  - 2021.08.17.18.54.02_veh-45_02202_02416
  - 2021.08.17.19.18.39_veh-08_00118_00178
  - 2021.08.17.19.18.39_veh-08_00208_00380
  - 2021.08.17.19.18.39_veh-08_00407_00595
  - 2021.08.17.19.18.39_veh-08_00696_00823
  - 2021.08.24.13.12.55_veh-45_00386_00472
  - 2021.08.24.13.12.55_veh-45_00507_00867
  - 2021.08.24.14.25.28_veh-42_00333_00472
  - 2021.08.24.14.35.46_veh-45_00011_00162
  - 2021.08.24.14.35.46_veh-45_00440_00501
  - 2021.08.24.14.35.46_veh-45_00549_00693
  - 2021.08.24.14.35.46_veh-45_01568_01663
  - 2021.08.24.15.09.18_veh-45_00216_00862
  - 2021.08.24.17.01.06_veh-45_00228_00689
  - 2021.08.24.17.01.06_veh-45_01557_01681
  - 2021.08.24.17.34.27_veh-45_00696_00786
  - 2021.08.24.17.34.27_veh-45_00808_00993
  - 2021.08.24.17.34.27_veh-45_01478_01553
  - 2021.08.24.17.37.11_veh-08_02359_02623
  - 2021.08.24.18.07.48_veh-45_00203_00300
  - 2021.08.24.18.07.48_veh-45_00873_01142
  - 2021.08.24.18.07.48_veh-45_01504_01722
  - 2021.08.24.18.30.46_veh-08_01674_01850
  - 2021.08.24.18.30.46_veh-08_01985_02093
  - 2021.08.24.18.30.46_veh-08_02327_02583
  - 2021.08.24.18.30.46_veh-08_02605_02732
  - 2021.08.24.19.30.33_veh-45_00290_00484
  - 2021.08.24.19.30.33_veh-45_01391_01523
  - 2021.08.24.20.03.01_veh-45_00021_00143
  - 2021.08.24.20.03.01_veh-45_00171_00238
  - 2021.08.24.20.03.01_veh-45_00269_00428
  - 2021.08.24.20.03.01_veh-45_00463_00588
  - 2021.08.24.20.03.01_veh-45_00687_00787
  - 2021.08.24.20.03.01_veh-45_00824_00888
  - 2021.08.31.11.47.30_veh-40_00248_00376
  - 2021.08.31.11.47.30_veh-40_00393_00847
  - 2021.08.31.11.47.30_veh-40_00919_01000
  - 2021.08.31.11.47.30_veh-40_01146_01347
  - 2021.08.31.11.47.30_veh-40_01362_01737
  - 2021.08.31.12.21.30_veh-40_00056_00155
  - 2021.08.31.12.21.30_veh-40_00248_00367
  - 2021.08.31.12.21.30_veh-40_00378_00527
  - 2021.08.31.12.21.30_veh-40_00538_00638
  - 2021.08.31.12.21.30_veh-40_00661_00762
  - 2021.08.31.12.21.30_veh-40_01485_01676
  - 2021.08.31.12.54.56_veh-40_00024_00106
  - 2021.08.31.12.54.56_veh-40_00305_00667
  - 2021.08.31.12.54.56_veh-40_00725_00909
  - 2021.08.31.12.54.56_veh-40_00921_01014
  - 2021.08.31.12.54.56_veh-40_01056_01183
  - 2021.08.31.12.54.56_veh-40_01249_01397
  - 2021.08.31.12.54.56_veh-40_01536_01758
  - 2021.08.31.13.27.52_veh-40_00058_00145
  - 2021.08.31.13.27.52_veh-40_00186_00414
  - 2021.08.31.13.27.52_veh-40_00688_00750
  - 2021.08.31.13.27.52_veh-40_00869_01319
  - 2021.08.31.13.27.52_veh-40_01330_01491
  - 2021.08.31.13.27.52_veh-40_01615_01687
  - 2021.08.31.14.01.15_veh-40_00304_00384
  - 2021.08.31.14.01.15_veh-40_00407_00497
  - 2021.08.31.14.01.15_veh-40_00573_00681
  - 2021.08.31.14.01.15_veh-40_00692_00977
  - 2021.08.31.14.01.15_veh-40_01109_01272
  - 2021.08.31.14.01.15_veh-40_01284_01345
  - 2021.08.31.14.01.15_veh-40_01576_01714
  - 2021.08.31.14.40.58_veh-40_00016_00084
  - 2021.08.31.14.40.58_veh-40_00125_00269
  - 2021.08.31.14.40.58_veh-40_00285_00456
  - 2021.08.31.14.40.58_veh-40_00467_00668
  - 2021.08.31.14.40.58_veh-40_00679_00892
  - 2021.08.31.14.40.58_veh-40_01022_01255
  - 2021.08.31.14.40.58_veh-40_01268_01618
  - 2021.08.31.16.37.21_veh-40_00016_00099
  - 2021.08.31.16.37.21_veh-40_00110_00187
  - 2021.08.31.16.37.21_veh-40_00198_00265
  - 2021.08.31.16.37.21_veh-40_00277_00417
  - 2021.08.31.16.37.21_veh-40_00429_00541
  - 2021.08.31.16.37.21_veh-40_00554_00733
  - 2021.08.31.16.37.21_veh-40_00798_00955
  - 2021.08.31.16.37.21_veh-40_01101_01177
  - 2021.08.31.16.37.21_veh-40_01247_01379
  - 2021.08.31.16.37.21_veh-40_01405_01642
  - 2021.08.31.16.37.21_veh-40_01655_01736
  - 2021.08.31.17.42.52_veh-40_00389_00526
  - 2021.08.31.17.42.52_veh-40_00551_00680
  - 2021.08.31.17.42.52_veh-40_00833_00953
  - 2021.08.31.17.42.52_veh-40_01033_01313
  - 2021.08.31.17.42.52_veh-40_01331_01444
  - 2021.08.31.17.42.52_veh-40_01551_01684
  - 2021.08.31.18.15.54_veh-40_00038_00199
  - 2021.08.31.18.15.54_veh-40_00227_00324
  - 2021.08.31.18.15.54_veh-40_00335_00568
  - 2021.08.31.18.15.54_veh-40_00579_00980
  - 2021.08.31.18.15.54_veh-40_01010_01094
  - 2021.08.31.18.15.54_veh-40_01143_01496
  - 2021.09.14.15.03.51_veh-45_00178_00336
  - 2021.09.14.15.03.51_veh-45_00390_00585
  - 2021.09.14.16.46.51_veh-45_00149_00900
  - 2021.09.14.16.46.51_veh-45_02322_02510
  - 2021.09.14.18.43.41_veh-45_00885_00952
  - 2021.09.14.18.43.41_veh-45_00965_01195
  - 2021.09.14.18.43.41_veh-45_01245_01529
  - 2021.09.14.18.43.41_veh-45_02296_02477
  - 2021.09.14.18.43.41_veh-45_02503_03013
  - 2021.09.14.19.46.05_veh-45_01937_02119
  - 2021.09.14.20.42.30_veh-45_00464_00579
  - 2021.09.14.20.42.30_veh-45_00805_01078
  - 2021.09.14.20.42.30_veh-45_01097_01242
  - 2021.09.14.20.42.30_veh-45_01603_01670
  - 2021.09.15.11.49.23_veh-28_00081_00237
  - 2021.09.15.11.49.23_veh-28_00280_00506
  - 2021.09.15.11.49.23_veh-28_00520_00669
  - 2021.09.15.11.49.23_veh-28_00767_00955
  - 2021.09.15.11.49.23_veh-28_01108_01493
  - 2021.09.15.11.49.23_veh-28_01869_02000
  - 2021.09.15.11.49.23_veh-28_02024_02091
  - 2021.09.15.11.49.23_veh-28_02192_02253
  - 2021.09.15.12.32.43_veh-28_00015_00093
  - 2021.09.15.12.32.43_veh-28_00202_00323
  - 2021.09.15.12.32.43_veh-28_00417_00527
  - 2021.09.15.12.32.43_veh-28_00625_00697
  - 2021.09.15.12.32.43_veh-28_00708_00866
  - 2021.09.15.12.32.43_veh-28_00973_01056
  - 2021.09.15.12.32.43_veh-28_01070_01157
  - 2021.09.15.12.32.43_veh-28_01238_01314
  - 2021.09.15.12.32.43_veh-28_01410_01501
  - 2021.09.15.12.32.43_veh-28_01513_01697
  - 2021.09.15.12.32.43_veh-28_02111_02342
  - 2021.09.15.13.12.49_veh-39_00022_00104
  - 2021.09.15.13.12.49_veh-39_00135_00467
  - 2021.09.15.13.12.49_veh-39_00541_00634
  - 2021.09.15.13.12.49_veh-39_00645_00802
  - 2021.09.15.13.12.49_veh-39_01049_01301
  - 2021.09.15.13.12.49_veh-39_01329_01520
  - 2021.09.15.13.12.49_veh-39_01532_01687
  - 2021.09.15.13.16.40_veh-28_00088_00157
  - 2021.09.15.13.16.40_veh-28_00180_00257
  - 2021.09.15.13.16.40_veh-28_00366_00631
  - 2021.09.15.13.16.40_veh-28_00642_01267
  - 2021.09.15.13.16.40_veh-28_01343_01432
  - 2021.09.15.13.16.40_veh-28_01473_01612
  - 2021.09.15.13.16.40_veh-28_01817_01902
  - 2021.09.15.13.16.40_veh-28_02072_02166
  - 2021.09.15.13.16.40_veh-28_02198_02321
  - 2021.09.15.13.52.55_veh-39_00016_00122
  - 2021.09.15.13.52.55_veh-39_00134_00215
  - 2021.09.15.13.52.55_veh-39_00371_00631
  - 2021.09.15.13.52.55_veh-39_00643_00807
  - 2021.09.15.13.52.55_veh-39_00818_01335
  - 2021.09.15.13.52.55_veh-39_01385_01446
  - 2021.09.15.14.00.15_veh-28_00288_00408
  - 2021.09.15.14.00.15_veh-28_00420_00578
  - 2021.09.15.14.00.15_veh-28_00770_00852
  - 2021.09.15.14.00.15_veh-28_00895_00981
  - 2021.09.15.14.00.15_veh-28_01274_01543
  - 2021.09.15.14.00.15_veh-28_01611_01874
  - 2021.09.15.14.00.15_veh-28_01953_02255
  - 2021.09.15.14.27.22_veh-39_00038_00414
  - 2021.09.15.14.27.22_veh-39_00473_00568
  - 2021.09.15.14.27.22_veh-39_00580_00654
  - 2021.09.15.14.27.22_veh-39_00665_00745
  - 2021.09.15.14.27.22_veh-39_00756_00838
  - 2021.09.15.14.27.22_veh-39_00868_01125
  - 2021.09.15.14.27.22_veh-39_01166_01252
  - 2021.09.15.14.27.22_veh-39_01281_01346
  - 2021.09.15.14.27.22_veh-39_01420_01480
  - 2021.09.15.14.27.22_veh-39_01491_01763
  - 2021.09.15.14.50.05_veh-28_00083_00152
  - 2021.09.15.14.50.05_veh-28_00182_00253
  - 2021.09.15.14.50.05_veh-28_00389_00508
  - 2021.09.15.14.50.05_veh-28_00578_00896
  - 2021.09.15.14.50.05_veh-28_01187_01281
  - 2021.09.15.14.50.05_veh-28_01392_01458
  - 2021.09.15.14.50.05_veh-28_01511_01690
  - 2021.09.15.14.50.05_veh-28_01740_01833
  - 2021.09.15.14.50.05_veh-28_02133_02222
  - 2021.09.15.15.02.19_veh-39_00105_00203
  - 2021.09.15.15.02.19_veh-39_00214_00558
  - 2021.09.15.15.02.19_veh-39_00856_01095
  - 2021.09.15.15.02.19_veh-39_01107_01666
  - 2021.09.15.15.34.53_veh-28_00030_00128
  - 2021.09.15.15.34.53_veh-28_00365_00501
  - 2021.09.15.15.34.53_veh-28_00512_01084
  - 2021.09.15.15.34.53_veh-28_01133_01234
  - 2021.09.15.15.34.53_veh-28_01303_01395
  - 2021.09.15.15.34.53_veh-28_01533_01596
  - 2021.09.15.15.34.53_veh-28_01639_01805
  - 2021.09.15.15.34.53_veh-28_01820_02314
  - 2021.09.15.16.17.26_veh-28_00586_00712
  - 2021.09.15.16.17.26_veh-28_00772_00880
  - 2021.09.15.16.17.26_veh-28_00937_01074
  - 2021.09.15.16.17.26_veh-28_01085_01182
  - 2021.09.15.16.17.26_veh-28_01370_01439
  - 2021.09.15.16.17.26_veh-28_01450_01544
  - 2021.09.15.16.17.26_veh-28_01581_01740
  - 2021.09.15.16.51.15_veh-28_00005_00160
  - 2021.09.15.16.51.15_veh-28_00176_00329
  - 2021.09.15.16.51.15_veh-28_00357_00430
  - 2021.09.15.16.51.15_veh-28_01225_01302
  - 2021.09.15.16.51.15_veh-28_01468_01533
  - 2021.09.15.16.51.15_veh-28_01698_01775
  - 2021.10.01.13.28.54_veh-28_00094_00181
  - 2021.10.01.13.28.54_veh-28_00405_00547
  - 2021.10.01.13.28.54_veh-28_00607_00973
  - 2021.10.01.13.28.54_veh-28_00995_01087
  - 2021.10.01.13.28.54_veh-28_01098_01337
  - 2021.10.01.13.28.54_veh-28_01421_01615
  - 2021.10.01.13.28.54_veh-28_01767_01883
  - 2021.10.01.14.20.36_veh-28_00038_00128
  - 2021.10.01.14.20.36_veh-28_00243_00388
  - 2021.10.01.14.20.36_veh-28_00475_00646
  - 2021.10.01.14.20.36_veh-28_00825_00919
  - 2021.10.01.14.20.36_veh-28_00931_01128
  - 2021.10.01.14.20.36_veh-28_01151_01286
  - 2021.10.01.14.20.36_veh-28_01415_01480
  - 2021.10.01.14.20.36_veh-28_01491_01630
  - 2021.10.01.15.32.11_veh-28_00025_00097
  - 2021.10.01.15.32.11_veh-28_00120_00248
  - 2021.10.01.15.32.11_veh-28_00291_00464
  - 2021.10.01.15.32.11_veh-28_00475_00930
  - 2021.10.01.15.32.11_veh-28_01000_01136
  - 2021.10.01.15.32.11_veh-28_01178_01392
  - 2021.10.01.17.52.06_veh-28_00098_00211
  - 2021.10.01.17.52.06_veh-28_00327_00427
  - 2021.10.01.17.52.06_veh-28_00450_00599
  - 2021.10.01.17.52.06_veh-28_00675_00737
  - 2021.10.01.17.52.06_veh-28_00748_00952
  - 2021.10.01.17.52.06_veh-28_01034_01107
  - 2021.10.01.17.52.06_veh-28_01141_01264
  - 2021.10.01.17.52.06_veh-28_01289_01353
  - 2021.10.01.17.52.06_veh-28_01364_01428
  - 2021.10.01.17.52.06_veh-28_01441_01573
  - 2021.10.01.17.52.06_veh-28_01622_01687
  - 2021.10.01.18.26.05_veh-28_00005_00413
  - 2021.10.01.18.26.05_veh-28_00481_00656
  - 2021.10.01.18.26.05_veh-28_00949_01041
  - 2021.10.01.18.26.05_veh-28_01081_01159
  - 2021.10.01.18.26.05_veh-28_01211_01323
  - 2021.10.01.18.26.05_veh-28_01689_01890
  - 2021.10.01.19.16.42_veh-28_00094_00216
  - 2021.10.01.19.16.42_veh-28_00274_00380
  - 2021.10.01.19.16.42_veh-28_00392_00906
  - 2021.10.01.19.16.42_veh-28_00917_01499
  - 2021.10.01.19.16.42_veh-28_01511_01624
  - 2021.10.01.19.16.42_veh-28_01731_01935
  - 2021.10.01.19.16.42_veh-28_02011_02410
  - 2021.10.01.19.16.42_veh-28_02447_02517
  - 2021.10.01.19.16.42_veh-28_02568_02833
  - 2021.10.01.19.16.42_veh-28_02903_03140
  - 2021.10.01.19.16.42_veh-28_03215_03296
  - 2021.10.01.19.16.42_veh-28_03307_03808
  - 2021.10.01.19.16.42_veh-28_03887_04040
  - 2021.10.05.04.03.05_veh-50_00058_00321
  - 2021.10.05.04.03.05_veh-50_00365_00493
  - 2021.10.05.04.03.05_veh-50_00536_00637
  - 2021.10.05.04.03.05_veh-50_00648_00744
  - 2021.10.05.04.03.05_veh-50_01003_01426
  - 2021.10.05.04.03.05_veh-50_01466_01790
  - 2021.10.05.04.38.41_veh-50_00014_00429
  - 2021.10.05.04.38.41_veh-50_00441_00515
  - 2021.10.05.04.38.41_veh-50_00576_00721
  - 2021.10.05.04.38.41_veh-50_00753_00956
  - 2021.10.05.04.38.41_veh-50_00996_01109
  - 2021.10.05.04.38.41_veh-50_01202_01296
  - 2021.10.05.06.24.06_veh-50_00021_00383
  - 2021.10.05.06.24.06_veh-50_00431_00527
  - 2021.10.05.06.24.06_veh-50_00717_01300
  - 2021.10.05.06.24.06_veh-50_01311_01409
  - 2021.10.05.06.24.06_veh-50_01420_01553
  - 2021.10.05.06.24.06_veh-50_01566_01672
  - 2021.10.05.06.31.40_veh-52_00005_00342
  - 2021.10.05.06.31.40_veh-52_00355_00454
  - 2021.10.05.06.31.40_veh-52_00465_00713
  - 2021.10.05.06.31.40_veh-52_00734_01305
  - 2021.10.05.06.31.40_veh-52_01316_01565
  - 2021.10.05.06.31.40_veh-52_01598_02013
  - 2021.10.05.06.57.40_veh-50_00025_00261
  - 2021.10.05.06.57.40_veh-50_00485_00624
  - 2021.10.05.06.57.40_veh-50_00665_00857
  - 2021.10.05.06.57.40_veh-50_00940_01105
  - 2021.10.05.06.57.40_veh-50_01131_01452
  - 2021.10.05.06.57.40_veh-50_01493_01624