_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'
num_history_frames: 4
num_future_frames: 10
frame_interval: 1
has_route: true
max_scenes: null
log_names:
  - 2021.06.09.18.23.43_veh-35_03609_03793
  - 2021.06.09.18.23.43_veh-35_03804_03956
  - 2021.06.09.18.23.43_veh-35_03967_05057
  - 2021.06.09.18.23.43_veh-35_05068_05186
  - 2021.06.09.18.23.43_veh-35_05198_05504
  - 2021.06.09.19.40.26_veh-12_00133_00268
  - 2021.06.09.19.40.26_veh-12_00279_01212
  - 2021.06.09.19.40.26_veh-12_01241_01510
  - 2021.06.09.19.40.26_veh-12_01525_02020
  - 2021.06.09.19.40.26_veh-12_02031_02228
  - 2021.06.09.20.26.11_veh-35_00026_00236
  - 2021.06.09.20.26.11_veh-35_00247_00529
  - 2021.06.09.20.26.11_veh-35_00540_00789
  - 2021.06.09.20.26.11_veh-35_00825_00942
  - 2021.06.09.20.26.11_veh-35_00970_01216
  - 2021.06.09.20.26.11_veh-35_01227_01514
  - 2021.06.14.11.44.56_veh-35_00059_00410
  - 2021.06.14.11.44.56_veh-35_00453_00731
  - 2021.06.14.11.44.56_veh-35_00742_00927
  - 2021.06.14.11.44.56_veh-35_00938_01134
  - 2021.06.14.11.44.56_veh-35_01145_01297
  - 2021.06.14.11.44.56_veh-35_01308_01584
  - 2021.06.14.11.44.56_veh-35_01595_01804
  - 2021.06.14.11.44.56_veh-35_01869_01972
  - 2021.06.14.11.44.56_veh-35_01983_02053
  - 2021.06.14.11.44.56_veh-35_02064_02388
  - 2021.06.14.11.44.56_veh-35_02399_02672
  - 2021.06.14.11.44.56_veh-35_02696_02932
  - 2021.06.14.11.44.56_veh-35_02983_03378
  - 2021.06.14.11.44.56_veh-35_03389_04017
  - 2021.06.14.11.44.56_veh-35_04178_05084
  - 2021.06.14.11.44.56_veh-35_05211_05338
  - 2021.06.14.13.27.42_veh-35_00005_00123
  - 2021.06.14.13.27.42_veh-35_00142_00231
  - 2021.06.14.13.27.42_veh-35_00243_00342
  - 2021.06.14.13.27.42_veh-35_00353_00531
  - 2021.06.14.13.27.42_veh-35_00542_00645
  - 2021.06.14.13.27.42_veh-35_00691_00798
  - 2021.06.14.13.27.42_veh-35_00842_00940
  - 2021.06.14.13.27.42_veh-35_01025_01086
  - 2021.06.14.13.27.42_veh-35_01160_01331
  - 2021.06.14.13.27.42_veh-35_01342_01461
  - 2021.06.14.13.27.42_veh-35_01472_01666
  - 2021.06.14.13.27.42_veh-35_01698_01822
  - 2021.06.14.13.27.42_veh-35_01854_01994
  - 2021.06.14.13.27.42_veh-35_02028_02106
  - 2021.06.14.13.27.42_veh-35_02117_02272
  - 2021.06.14.13.27.42_veh-35_02283_02603
  - 2021.06.14.13.27.42_veh-35_02614_02842
  - 2021.06.14.13.27.42_veh-35_02853_02953
  - 2021.06.14.13.27.42_veh-35_03142_03404
  - 2021.06.14.13.27.42_veh-35_03463_03587
  - 2021.06.14.13.27.42_veh-35_03624_03705
  - 2021.06.14.13.27.42_veh-35_03806_03990
  - 2021.06.14.13.27.42_veh-35_04001_04236
  - 2021.06.14.13.27.42_veh-35_04362_04572
  - 2021.06.14.13.27.42_veh-35_04596_04692
  - 2021.06.14.13.27.42_veh-35_04704_04782
  - 2021.06.14.13.27.42_veh-35_04793_04883
  - 2021.06.14.13.27.42_veh-35_04894_05018
  - 2021.06.14.13.27.42_veh-35_05029_05340
  - 2021.06.14.13.28.41_veh-12_00005_00158
  - 2021.06.14.13.28.41_veh-12_00169_00783
  - 2021.06.14.13.28.41_veh-12_00906_01063
  - 2021.06.14.13.28.41_veh-12_01138_01284
  - 2021.06.14.13.28.41_veh-12_01313_01541
  - 2021.06.14.13.28.41_veh-12_01591_01695
  - 2021.06.14.13.28.41_veh-12_01779_02059
  - 2021.06.14.13.28.41_veh-12_02070_02140
  - 2021.06.14.13.28.41_veh-12_02245_02340
  - 2021.06.14.13.28.41_veh-12_02414_02601
  - 2021.06.14.13.28.41_veh-12_02612_02703
  - 2021.06.14.13.28.41_veh-12_02845_03153
  - 2021.06.14.13.28.41_veh-12_03221_03301
  - 2021.06.14.13.28.41_veh-12_03312_03409
  - 2021.06.14.13.28.41_veh-12_03457_03543
  - 2021.06.14.13.28.41_veh-12_03763_03829
  - 2021.06.14.13.28.41_veh-12_03841_04014
  - 2021.06.14.13.28.41_veh-12_04090_04289
  - 2021.06.14.13.28.41_veh-12_04300_04506
  - 2021.06.14.13.28.41_veh-12_04530_04609
  - 2021.06.14.13.28.41_veh-12_04719_04892
  - 2021.06.14.13.28.41_veh-12_04903_05107
  - 2021.06.14.13.28.41_veh-12_05118_05258
  - 2021.06.14.13.28.41_veh-12_05269_05369
  - 2021.06.14.14.03.45_veh-38_00088_00769
  - 2021.06.14.14.03.45_veh-38_00780_01007
  - 2021.06.14.14.03.45_veh-38_01018_01144
  - 2021.06.14.14.03.45_veh-38_01155_01358
  - 2021.06.14.14.03.45_veh-38_01369_01458
  - 2021.06.14.14.03.45_veh-38_01547_01613
  - 2021.06.14.14.03.45_veh-38_01624_01811
  - 2021.06.14.14.03.45_veh-38_01927_01996
  - 2021.06.14.14.03.45_veh-38_02007_02072
  - 2021.06.14.14.03.45_veh-38_02112_03169
  - 2021.06.14.14.03.45_veh-38_03180_03766
  - 2021.06.14.14.03.45_veh-38_03777_04059
  - 2021.06.14.14.03.45_veh-38_04137_04387
  - 2021.06.14.14.03.45_veh-38_04398_04488
  - 2021.06.14.14.03.45_veh-38_04499_05170
  - 2021.06.14.14.03.45_veh-38_05222_05347
  - 2021.06.14.14.25.15_veh-26_00398_00578
  - 2021.06.14.14.25.15_veh-26_00597_00827
  - 2021.06.14.14.25.15_veh-26_00867_01088
  - 2021.06.14.14.25.15_veh-26_01236_01585
  - 2021.06.14.14.25.15_veh-26_01600_01699
  - 2021.06.14.14.25.15_veh-26_01752_01813
  - 2021.06.14.14.25.15_veh-26_01835_01960
  - 2021.06.14.14.25.15_veh-26_02009_02099
  - 2021.06.14.14.25.15_veh-26_02179_02316
  - 2021.06.14.14.25.15_veh-26_02376_02575
  - 2021.06.14.14.25.15_veh-26_02586_02648
  - 2021.06.14.14.25.15_veh-26_02659_02759
  - 2021.06.14.14.25.15_veh-26_02770_02830
  - 2021.06.14.14.25.15_veh-26_02841_02921
  - 2021.06.14.14.25.15_veh-26_02932_03190
  - 2021.06.14.14.25.15_veh-26_03201_03386
  - 2021.06.14.14.25.15_veh-26_03415_03581
  - 2021.06.14.14.25.15_veh-26_03592_03664
  - 2021.06.14.14.25.15_veh-26_03675_03860
  - 2021.06.14.14.25.15_veh-26_03871_03953
  - 2021.06.14.14.25.15_veh-26_03964_04278
  - 2021.06.14.14.25.15_veh-26_04289_04406
  - 2021.06.14.14.25.15_veh-26_04417_04531
  - 2021.06.14.14.25.15_veh-26_04542_04617
  - 2021.06.14.14.25.15_veh-26_04629_04724
  - 2021.06.14.14.25.15_veh-26_04735_04829
  - 2021.06.14.14.25.15_veh-26_04936_05073
  - 2021.06.14.14.25.15_veh-26_05108_05312
  - 2021.06.14.16.32.09_veh-35_00016_00087
  - 2021.06.14.16.32.09_veh-35_00100_00272
  - 2021.06.14.16.32.09_veh-35_00283_00357
  - 2021.06.14.16.32.09_veh-35_00429_00563
  - 2021.06.14.16.32.09_veh-35_00574_00989
  - 2021.06.14.16.32.09_veh-35_01219_01415
  - 2021.06.14.16.32.09_veh-35_01489_01563
  - 2021.06.14.16.32.09_veh-35_01620_01699
  - 2021.06.14.16.32.09_veh-35_01710_01770
  - 2021.06.14.16.32.09_veh-35_01781_02379
  - 2021.06.14.16.32.09_veh-35_02435_02526
  - 2021.06.14.16.32.09_veh-35_02537_02597
  - 2021.06.14.16.32.09_veh-35_02618_02873
  - 2021.06.14.16.32.09_veh-35_02928_03118
  - 2021.06.14.16.32.09_veh-35_03129_03220
  - 2021.06.14.16.32.09_veh-35_03231_03426
  - 2021.06.14.16.32.09_veh-35_03438_03580
  - 2021.06.14.16.32.09_veh-35_03635_03792
  - 2021.06.14.16.32.09_veh-35_03803_04103
  - 2021.06.14.16.32.09_veh-35_04114_04359
  - 2021.06.14.16.32.09_veh-35_04370_04488
  - 2021.06.14.16.32.09_veh-35_04516_04698
  - 2021.06.14.16.32.09_veh-35_04749_05027
  - 2021.06.14.16.32.09_veh-35_05038_05402
  - 2021.06.14.16.48.02_veh-12_00009_00127
  - 2021.06.14.16.48.02_veh-12_00285_00574
  - 2021.06.14.16.48.02_veh-12_00585_00672
  - 2021.06.14.16.48.02_veh-12_00721_00828
  - 2021.06.14.16.48.02_veh-12_00839_00980
  - 2021.06.14.16.48.02_veh-12_01020_01720
  - 2021.06.14.16.48.02_veh-12_01732_01853
  - 2021.06.14.16.48.02_veh-12_01880_02198
  - 2021.06.14.16.48.02_veh-12_02317_02401
  - 2021.06.14.16.48.02_veh-12_02412_02506
  - 2021.06.14.16.48.02_veh-12_02517_02590
  - 2021.06.14.16.48.02_veh-12_02601_02668
  - 2021.06.14.16.48.02_veh-12_02679_02850
  - 2021.06.14.16.48.02_veh-12_02861_03047
  - 2021.06.14.16.48.02_veh-12_03091_03461
  - 2021.06.14.16.48.02_veh-12_03472_03779
  - 2021.06.14.16.48.02_veh-12_03790_04046
  - 2021.06.14.16.48.02_veh-12_04057_04438
  - 2021.06.14.16.48.02_veh-12_04492_04604
  - 2021.06.14.16.48.02_veh-12_04615_04689
  - 2021.06.14.16.48.02_veh-12_04783_04967
  - 2021.06.14.16.48.02_veh-12_04978_05337
  - 2021.06.14.17.26.26_veh-38_00104_00944
  - 2021.06.14.17.26.26_veh-38_00955_01067
  - 2021.06.14.17.26.26_veh-38_01078_01166
  - 2021.06.14.17.26.26_veh-38_01177_01256
  - 2021.06.14.17.26.26_veh-38_01293_01488
  - 2021.06.14.17.26.26_veh-38_01499_01849
  - 2021.06.14.17.26.26_veh-38_01860_02729
  - 2021.06.14.17.26.26_veh-38_02740_03036
  - 2021.06.14.17.26.26_veh-38_03086_03150
  - 2021.06.14.17.26.26_veh-38_03162_03227
  - 2021.06.14.17.26.26_veh-38_03238_03403
  - 2021.06.14.17.26.26_veh-38_03414_03761
  - 2021.06.14.17.26.26_veh-38_03772_03967
  - 2021.06.14.17.26.26_veh-38_04030_04274
  - 2021.06.14.17.26.26_veh-38_04285_04392
  - 2021.06.14.17.26.26_veh-38_04403_04533
  - 2021.06.14.17.26.26_veh-38_04544_04920
  - 2021.06.14.17.26.26_veh-38_04931_05037
  - 2021.06.14.17.26.26_veh-38_05048_05270
  - 2021.06.14.17.26.26_veh-38_05281_05444
  - 2021.06.14.17.26.26_veh-38_05455_05749
  - 2021.06.14.17.26.26_veh-38_05760_05896
  - 2021.06.14.18.13.35_veh-26_00027_00215
  - 2021.06.14.18.13.35_veh-26_00259_00374
  - 2021.06.14.18.13.35_veh-26_00385_00471
  - 2021.06.14.18.13.35_veh-26_00522_00702
  - 2021.06.14.18.13.35_veh-26_00713_00818
  - 2021.06.14.18.13.35_veh-26_00863_00924
  - 2021.06.14.18.13.35_veh-26_00954_01050
  - 2021.06.14.18.13.35_veh-26_01062_01139
  - 2021.06.14.18.13.35_veh-26_01150_01320
  - 2021.06.14.18.13.35_veh-26_01331_01526
  - 2021.06.14.18.13.35_veh-26_01537_01717
  - 2021.06.14.18.13.35_veh-26_01728_01918
  - 2021.06.14.18.13.35_veh-26_01931_02022
  - 2021.06.14.18.13.35_veh-26_02033_02313
  - 2021.06.14.18.13.35_veh-26_02324_02430
  - 2021.06.14.18.13.35_veh-26_02441_02514
  - 2021.06.14.18.13.35_veh-26_02724_02920
  - 2021.06.14.18.13.35_veh-26_03030_03119
  - 2021.06.14.18.13.35_veh-26_03130_03197
  - 2021.06.14.18.13.35_veh-26_03258_03349
  - 2021.06.14.18.13.35_veh-26_03401_03691
  - 2021.06.14.18.13.35_veh-26_03853_03946
  - 2021.06.14.18.13.35_veh-26_03957_04032
  - 2021.06.14.18.13.35_veh-26_04058_04170
  - 2021.06.14.18.13.35_veh-26_04204_04323
  - 2021.06.14.18.13.35_veh-26_04412_04536
  - 2021.06.14.18.13.35_veh-26_04547_04710
  - 2021.06.14.18.13.35_veh-26_04721_04800
  - 2021.06.14.18.13.35_veh-26_04811_04953
  - 2021.06.14.18.13.35_veh-26_04964_05075
  - 2021.06.14.18.13.35_veh-26_05205_05275
  - 2021.06.14.18.13.35_veh-26_05286_05411
  - 2021.06.14.18.13.35_veh-26_05422_05488
  - 2021.06.14.18.13.35_veh-26_05600_05660
  - 2021.06.14.18.13.35_veh-26_05671_05749
  - 2021.06.14.18.33.41_veh-35_00016_00213
  - 2021.06.14.18.33.41_veh-35_00224_00344
  - 2021.06.14.18.33.41_veh-35_00355_00477
  - 2021.06.14.18.33.41_veh-35_00488_00562
  - 2021.06.14.18.33.41_veh-35_00573_00643
  - 2021.06.14.18.33.41_veh-35_00654_00887
  - 2021.06.14.18.33.41_veh-35_00898_01182
  - 2021.06.14.18.33.41_veh-35_01193_01304
  - 2021.06.14.18.33.41_veh-35_01363_01636
  - 2021.06.14.18.33.41_veh-35_01647_01714
  - 2021.06.14.18.33.41_veh-35_01739_01918
  - 2021.06.14.18.33.41_veh-35_01970_02043
  - 2021.06.14.18.33.41_veh-35_02054_02129
  - 2021.06.14.18.33.41_veh-35_02140_02328
  - 2021.06.14.18.33.41_veh-35_02339_02447
  - 2021.06.14.18.33.41_veh-35_02521_03356
  - 2021.06.14.18.33.41_veh-35_03367_03508
  - 2021.06.14.18.33.41_veh-35_03575_03668
  - 2021.06.14.18.33.41_veh-35_03679_03787
  - 2021.06.14.18.33.41_veh-35_03798_03867
  - 2021.06.14.18.33.41_veh-35_03901_04264
  - 2021.06.14.18.33.41_veh-35_04275_04435
  - 2021.06.14.18.33.41_veh-35_04446_04756
  - 2021.06.14.18.33.41_veh-35_04768_04894
  - 2021.06.14.18.33.41_veh-35_04905_05090
  - 2021.06.14.18.42.45_veh-12_00016_00185
  - 2021.06.14.18.42.45_veh-12_00364_00501
  - 2021.06.14.18.42.45_veh-12_00547_00777
  - 2021.06.14.18.42.45_veh-12_00789_00920
  - 2021.06.14.18.42.45_veh-12_00968_01052
  - 2021.06.14.18.42.45_veh-12_01065_01152
  - 2021.06.14.18.42.45_veh-12_01253_01334
  - 2021.06.14.18.42.45_veh-12_01345_01523
  - 2021.06.14.18.42.45_veh-12_01535_01612
  - 2021.06.14.18.42.45_veh-12_01680_01744
  - 2021.06.14.18.42.45_veh-12_01762_02072
  - 2021.06.14.18.42.45_veh-12_02099_02167
  - 2021.06.14.18.42.45_veh-12_02233_02300
  - 2021.06.14.18.42.45_veh-12_02318_02407
  - 2021.06.14.18.42.45_veh-12_02520_02585
  - 2021.06.14.18.42.45_veh-12_02596_02661
  - 2021.06.14.18.42.45_veh-12_02737_02967
  - 2021.06.14.18.42.45_veh-12_02978_03068
  - 2021.06.14.18.42.45_veh-12_03200_03329
  - 2021.06.14.18.42.45_veh-12_03340_03403
  - 2021.06.14.18.42.45_veh-12_03445_03902
  - 2021.06.14.18.42.45_veh-12_03913_04017
  - 2021.06.14.18.42.45_veh-12_04086_04221
  - 2021.06.14.18.42.45_veh-12_04233_04472
  - 2021.06.14.18.42.45_veh-12_04534_04609
  - 2021.06.14.18.42.45_veh-12_04620_04742
  - 2021.06.14.18.42.45_veh-12_04838_04927
  - 2021.06.14.18.42.45_veh-12_05000_05079
  - 2021.06.14.18.42.45_veh-12_05170_05261
  - 2021.06.14.19.22.11_veh-38_00040_00464
  - 2021.06.14.19.22.11_veh-38_00572_00648
  - 2021.06.14.19.22.11_veh-38_00675_00889
  - 2021.06.14.19.22.11_veh-38_00910_01029
  - 2021.06.14.19.22.11_veh-38_01134_01389
  - 2021.06.14.19.22.11_veh-38_01400_01469
  - 2021.06.14.19.22.11_veh-38_01480_01860
  - 2021.06.14.19.22.11_veh-38_01871_02040
  - 2021.06.14.19.22.11_veh-38_02051_02264
  - 2021.06.14.19.22.11_veh-38_02275_02455
  - 2021.06.14.19.22.11_veh-38_02466_02675
  - 2021.06.14.19.22.11_veh-38_02686_02846
  - 2021.06.14.19.22.11_veh-38_02857_03230
  - 2021.06.14.19.22.11_veh-38_03242_03907