defaults:
  - network: unified

_target_: navsim.agents.dynamo.navsim_config.DynamoConfig
_convert_: 'all'

trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5

latent: False
