hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common
  job:
    chdir: False

defaults:
  - default_common
  - default_evaluation
  - ddp
  - agent: constant_velocity_agent
  - _self_
  - override train_test_split: navtest

"team_name": VAI # The team name
"authors": DynamoTeam  # The team members
"email": ellingtonkirby31@gmail.com # email of the corresponding team member
"institution": VAI # affiliation of the team
"country": France  # country or region of the team, e.g. China
