_target_: navsim.agents.dynamo.models.ego_encoders.encoders.LinearEgoEncoder
data_fields:
  ego_velocity:
    dim: 2
    drop: 0.0
  ego_acceleration:   
    dim: 2
    drop: 0.0
  high_level_command:
    dim: 4
    drop: 0.0
  ego_pose:
    dim: 3
    drop: 0.0
out_channels: ${agent.config.network.planner_channels}