defaults:
  - image_encoder: resnet34
  - projector_image: simplebev
  - sensor_fusion: agg
  - sensor_encoder: imagecnn
  - ego_encoder: linear
  - ego_sensors_fusion: concat_linear_temporal
  - planner_backbone: simple
  - _self_

# define the network
_target_: navsim.agents.dynamo.models.planners.unified.UnifiedPlanner

sensor_channels: 256
planner_channels: 512